#ifndef RESOURCE_CONFIG_H
#define RESOURCE_CONFIG_H

/* Numeric GPIO identifiers keep this contract usable by host-side tests. */
#define RESOURCE_PORT_A                 0U
#define RESOURCE_PORT_B                 1U
#define RESOURCE_PORT_C                 2U

#define RESOURCE_W25Q128_CS_PORT        RESOURCE_PORT_A
#define RESOURCE_W25Q128_CS_PIN         15U
#define RESOURCE_TFT_RESET_PORT         RESOURCE_PORT_C
#define RESOURCE_TFT_RESET_PIN          13U

#define RESOURCE_ENCODER_A_PORT         RESOURCE_PORT_B
#define RESOURCE_ENCODER_A_PIN          3U
#define RESOURCE_ENCODER_B_PORT         RESOURCE_PORT_B
#define RESOURCE_ENCODER_B_PIN          4U
#define RESOURCE_ENCODER_BUTTON_PORT    RESOURCE_PORT_B
#define RESOURCE_ENCODER_BUTTON_PIN     5U
#define RESOURCE_ENCODER_USES_GPIO_POLLING 1U

#define RESOURCE_TIMER_SYSTEM_TICK      0U
#define RESOURCE_TIMER_POWER_OUTPUT     1U
#define RESOURCE_TIMER_STEPPER_RESERVED 2U
#define RESOURCE_TIMER_UI_PWM           3U
#define RESOURCE_TIMER_RGB_STRIPS       4U

#define RESOURCE_PTC_TIMER              RESOURCE_TIMER_POWER_OUTPUT
#define RESOURCE_PTC_CHANNEL            1U
#define RESOURCE_FAN_TIMER              RESOURCE_TIMER_POWER_OUTPUT
#define RESOURCE_FAN_CHANNEL            4U
#define RESOURCE_TFT_BACKLIGHT_TIMER    RESOURCE_TIMER_UI_PWM
#define RESOURCE_TFT_BACKLIGHT_CHANNEL  3U
#define RESOURCE_BUZZER_TIMER           RESOURCE_TIMER_UI_PWM
#define RESOURCE_BUZZER_CHANNEL         4U

#endif /* RESOURCE_CONFIG_H */
